# https://yazi-rs.github.io/docs/configuration/keymap/

[[mgr.prepend_keymap]]
on   = ["z"]
run  = "plugin zoxide"
desc = "Jump to a directory using zoxide"

[[mgr.prepend_keymap]]
on   = ["Z"]
run  = "plugin fzf"
desc = "Jump to a file/directory using fzf"

[[mgr.prepend_keymap]]
on   = ["g", "m"]
run  = "cd /media"
desc = "Go to mounted media (USB drives)"

[[mgr.prepend_keymap]]
on   = ["g", "l"]
run  = '''shell 'lazygit' --block'''
desc = "Open lazygit in current directory"

[[mgr.prepend_keymap]]
on   = ["g", "v"]
run  = '''shell 'code "$PWD"' --block'''
desc = "Open VS Code in current directory"   